### ISSUE TITLE
Unnecessarily printed stacktraces in REST API

### ISSUE THREAD

**Issue by jamesrdi** [kadai-io/kadai#45]
TODO: We have to try first if we can shorten the error

It would be better not to print the full stacktrace in precise error case

2023-03-24T08:56:37.5119304Z 2023-03-24 08:56:37.482 ERROR 1876 --- [-auto-52-exec-1] p.t.c.rest.TaskanaRestExceptionHandler : Error occurred during processing of rest request: ExceptionRepresentationModel [error=ErrorCode [key=CLASSIFICATION_WITH_ID_NOT_FOUND, messageVariables={classificationId=CLI:200000000000000000000000000000000004}], status=404, exception=pro.taskana.classification.api.exceptions.ClassificationNotFoundException, message=Classification with id 'CLI:200000000000000000000000000000000004' wasn't found, path=/api/v1/classifications/CLI:200000000000000000000000000000000004]
2023-03-24T08:56:37.5120804Z
2023-03-24T08:56:37.5121963Z pro.taskana.classification.api.exceptions.ClassificationNotFoundException: Classification with id 'CLI:200000000000000000000000000000000004' wasn't found
2023-03-24T08:56:37.5123737Z at pro.taskana.classification.internal.ClassificationServiceImpl.getClassification(ClassificationServiceImpl.java:100) ~[taskana-core-6.0.2.jar:6.0.2]
2023-03-24T08:56:37.5125181Z at pro.taskana.classification.rest.ClassificationController.getClassification(ClassificationController.java:110) ~[classes/:na]
2023-03-24T08:56:37.5126239Z at pro.taskana.classification.rest.ClassificationController$$FastClassBySpringCGLIB$$80c77314.invoke() ~[classes/:na]
2023-03-24T08:56:37.5127731Z at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.25.jar:5.3.25]

**Comment by bruderj15** [comment]
The error mentioned results from below helper in [KadaiRestExceptionHandler](https://github.com/kadai-io/kadai/blob/master/rest/kadai-rest-spring/src/main/java/io/kadai/common/rest/KadaiRestExceptionHandler.java):
```java
  private ResponseEntity<Object> buildResponse(
      ErrorCode errorCode, Throwable ex, WebRequest req, HttpStatus status) {
    ExceptionRepresentationModel errorData =
        new ExceptionRepresentationModel(errorCode, status, ex, req);
    logger.error(
        String.format("Error occurred during processing of rest request: %s", errorData), ex);
    return ResponseEntity.status(status).body(errorData);
  }
```
This helper is intended for internal errors (5xx), which at best never occure at all.
Any internal error is an actual error, some state that shall never be reached.
Therefore, logging the entire stack-trace with level `error` seems to be the right decision here.

However, the usage does not follow it's intention as `buildResponse` is used for all kinds of exceptions such as 
`KadaiException` or `MaxUploadSizeExceededException` and many more.

In my opinion we should:
- get rid of `private static final Map<String, HttpStatus> HTTP_STATUS_BY_ERROR_CODE_KEY` for looking up stati,
- instead add handlers for all most-specific exceptions,
- treat handlers for non-specific exceptions such as `KadaiException` as a sink for uncovered cases and
- use helpers for the implementation of the most-specific exceptions handlers
